// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"tmail/ent/attachment"
	"tmail/ent/envelope"
	"tmail/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AttachmentUpdate is the builder for updating Attachment entities.
type AttachmentUpdate struct {
	config
	hooks    []Hook
	mutation *AttachmentMutation
}

// Where appends a list predicates to the AttachmentUpdate builder.
func (_u *AttachmentUpdate) Where(ps ...predicate.Attachment) *AttachmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetFilename sets the "filename" field.
func (_u *AttachmentUpdate) SetFilename(v string) *AttachmentUpdate {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *AttachmentUpdate) SetNillableFilename(v *string) *AttachmentUpdate {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetFilepath sets the "filepath" field.
func (_u *AttachmentUpdate) SetFilepath(v string) *AttachmentUpdate {
	_u.mutation.SetFilepath(v)
	return _u
}

// SetNillableFilepath sets the "filepath" field if the given value is not nil.
func (_u *AttachmentUpdate) SetNillableFilepath(v *string) *AttachmentUpdate {
	if v != nil {
		_u.SetFilepath(*v)
	}
	return _u
}

// SetContentType sets the "contentType" field.
func (_u *AttachmentUpdate) SetContentType(v string) *AttachmentUpdate {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "contentType" field if the given value is not nil.
func (_u *AttachmentUpdate) SetNillableContentType(v *string) *AttachmentUpdate {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetOwnerID sets the "owner" edge to the Envelope entity by ID.
func (_u *AttachmentUpdate) SetOwnerID(id int) *AttachmentUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the Envelope entity by ID if the given value is not nil.
func (_u *AttachmentUpdate) SetNillableOwnerID(id *int) *AttachmentUpdate {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the Envelope entity.
func (_u *AttachmentUpdate) SetOwner(v *Envelope) *AttachmentUpdate {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the AttachmentMutation object of the builder.
func (_u *AttachmentUpdate) Mutation() *AttachmentMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the Envelope entity.
func (_u *AttachmentUpdate) ClearOwner() *AttachmentUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AttachmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AttachmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AttachmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AttachmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AttachmentUpdate) check() error {
	if v, ok := _u.mutation.Filename(); ok {
		if err := attachment.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "Attachment.filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Filepath(); ok {
		if err := attachment.FilepathValidator(v); err != nil {
			return &ValidationError{Name: "filepath", err: fmt.Errorf(`ent: validator failed for field "Attachment.filepath": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentType(); ok {
		if err := attachment.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "contentType", err: fmt.Errorf(`ent: validator failed for field "Attachment.contentType": %w`, err)}
		}
	}
	return nil
}

func (_u *AttachmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(attachment.Table, attachment.Columns, sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(attachment.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.Filepath(); ok {
		_spec.SetField(attachment.FieldFilepath, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(attachment.FieldContentType, field.TypeString, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attachment.OwnerTable,
			Columns: []string{attachment.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(envelope.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attachment.OwnerTable,
			Columns: []string{attachment.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(envelope.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{attachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AttachmentUpdateOne is the builder for updating a single Attachment entity.
type AttachmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AttachmentMutation
}

// SetFilename sets the "filename" field.
func (_u *AttachmentUpdateOne) SetFilename(v string) *AttachmentUpdateOne {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *AttachmentUpdateOne) SetNillableFilename(v *string) *AttachmentUpdateOne {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetFilepath sets the "filepath" field.
func (_u *AttachmentUpdateOne) SetFilepath(v string) *AttachmentUpdateOne {
	_u.mutation.SetFilepath(v)
	return _u
}

// SetNillableFilepath sets the "filepath" field if the given value is not nil.
func (_u *AttachmentUpdateOne) SetNillableFilepath(v *string) *AttachmentUpdateOne {
	if v != nil {
		_u.SetFilepath(*v)
	}
	return _u
}

// SetContentType sets the "contentType" field.
func (_u *AttachmentUpdateOne) SetContentType(v string) *AttachmentUpdateOne {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "contentType" field if the given value is not nil.
func (_u *AttachmentUpdateOne) SetNillableContentType(v *string) *AttachmentUpdateOne {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetOwnerID sets the "owner" edge to the Envelope entity by ID.
func (_u *AttachmentUpdateOne) SetOwnerID(id int) *AttachmentUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the Envelope entity by ID if the given value is not nil.
func (_u *AttachmentUpdateOne) SetNillableOwnerID(id *int) *AttachmentUpdateOne {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the Envelope entity.
func (_u *AttachmentUpdateOne) SetOwner(v *Envelope) *AttachmentUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the AttachmentMutation object of the builder.
func (_u *AttachmentUpdateOne) Mutation() *AttachmentMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the Envelope entity.
func (_u *AttachmentUpdateOne) ClearOwner() *AttachmentUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// Where appends a list predicates to the AttachmentUpdate builder.
func (_u *AttachmentUpdateOne) Where(ps ...predicate.Attachment) *AttachmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AttachmentUpdateOne) Select(field string, fields ...string) *AttachmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Attachment entity.
func (_u *AttachmentUpdateOne) Save(ctx context.Context) (*Attachment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AttachmentUpdateOne) SaveX(ctx context.Context) *Attachment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AttachmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AttachmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AttachmentUpdateOne) check() error {
	if v, ok := _u.mutation.Filename(); ok {
		if err := attachment.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "Attachment.filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Filepath(); ok {
		if err := attachment.FilepathValidator(v); err != nil {
			return &ValidationError{Name: "filepath", err: fmt.Errorf(`ent: validator failed for field "Attachment.filepath": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentType(); ok {
		if err := attachment.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "contentType", err: fmt.Errorf(`ent: validator failed for field "Attachment.contentType": %w`, err)}
		}
	}
	return nil
}

func (_u *AttachmentUpdateOne) sqlSave(ctx context.Context) (_node *Attachment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(attachment.Table, attachment.Columns, sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Attachment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, attachment.FieldID)
		for _, f := range fields {
			if !attachment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != attachment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(attachment.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.Filepath(); ok {
		_spec.SetField(attachment.FieldFilepath, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(attachment.FieldContentType, field.TypeString, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attachment.OwnerTable,
			Columns: []string{attachment.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(envelope.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attachment.OwnerTable,
			Columns: []string{attachment.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(envelope.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Attachment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{attachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
