// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"tmail/ent/attachment"
	"tmail/ent/envelope"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EnvelopeCreate is the builder for creating a Envelope entity.
type EnvelopeCreate struct {
	config
	mutation *EnvelopeMutation
	hooks    []Hook
}

// SetTo sets the "to" field.
func (_c *EnvelopeCreate) SetTo(v string) *EnvelopeCreate {
	_c.mutation.SetTo(v)
	return _c
}

// SetFrom sets the "from" field.
func (_c *EnvelopeCreate) SetFrom(v string) *EnvelopeCreate {
	_c.mutation.SetFrom(v)
	return _c
}

// SetSubject sets the "subject" field.
func (_c *EnvelopeCreate) SetSubject(v string) *EnvelopeCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_c *EnvelopeCreate) SetNillableSubject(v *string) *EnvelopeCreate {
	if v != nil {
		_c.SetSubject(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *EnvelopeCreate) SetContent(v string) *EnvelopeCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *EnvelopeCreate) SetNillableContent(v *string) *EnvelopeCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EnvelopeCreate) SetCreatedAt(v time.Time) *EnvelopeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EnvelopeCreate) SetNillableCreatedAt(v *time.Time) *EnvelopeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (_c *EnvelopeCreate) AddAttachmentIDs(ids ...string) *EnvelopeCreate {
	_c.mutation.AddAttachmentIDs(ids...)
	return _c
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (_c *EnvelopeCreate) AddAttachments(v ...*Attachment) *EnvelopeCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAttachmentIDs(ids...)
}

// Mutation returns the EnvelopeMutation object of the builder.
func (_c *EnvelopeCreate) Mutation() *EnvelopeMutation {
	return _c.mutation
}

// Save creates the Envelope in the database.
func (_c *EnvelopeCreate) Save(ctx context.Context) (*Envelope, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EnvelopeCreate) SaveX(ctx context.Context) *Envelope {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnvelopeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnvelopeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EnvelopeCreate) defaults() {
	if _, ok := _c.mutation.Subject(); !ok {
		v := envelope.DefaultSubject
		_c.mutation.SetSubject(v)
	}
	if _, ok := _c.mutation.Content(); !ok {
		v := envelope.DefaultContent
		_c.mutation.SetContent(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := envelope.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EnvelopeCreate) check() error {
	if _, ok := _c.mutation.To(); !ok {
		return &ValidationError{Name: "to", err: errors.New(`ent: missing required field "Envelope.to"`)}
	}
	if v, ok := _c.mutation.To(); ok {
		if err := envelope.ToValidator(v); err != nil {
			return &ValidationError{Name: "to", err: fmt.Errorf(`ent: validator failed for field "Envelope.to": %w`, err)}
		}
	}
	if _, ok := _c.mutation.From(); !ok {
		return &ValidationError{Name: "from", err: errors.New(`ent: missing required field "Envelope.from"`)}
	}
	if v, ok := _c.mutation.From(); ok {
		if err := envelope.FromValidator(v); err != nil {
			return &ValidationError{Name: "from", err: fmt.Errorf(`ent: validator failed for field "Envelope.from": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "Envelope.subject"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Envelope.content"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Envelope.created_at"`)}
	}
	return nil
}

func (_c *EnvelopeCreate) sqlSave(ctx context.Context) (*Envelope, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EnvelopeCreate) createSpec() (*Envelope, *sqlgraph.CreateSpec) {
	var (
		_node = &Envelope{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(envelope.Table, sqlgraph.NewFieldSpec(envelope.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.To(); ok {
		_spec.SetField(envelope.FieldTo, field.TypeString, value)
		_node.To = value
	}
	if value, ok := _c.mutation.From(); ok {
		_spec.SetField(envelope.FieldFrom, field.TypeString, value)
		_node.From = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(envelope.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(envelope.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(envelope.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   envelope.AttachmentsTable,
			Columns: []string{envelope.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EnvelopeCreateBulk is the builder for creating many Envelope entities in bulk.
type EnvelopeCreateBulk struct {
	config
	err      error
	builders []*EnvelopeCreate
}

// Save creates the Envelope entities in the database.
func (_c *EnvelopeCreateBulk) Save(ctx context.Context) ([]*Envelope, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Envelope, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EnvelopeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EnvelopeCreateBulk) SaveX(ctx context.Context) []*Envelope {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnvelopeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnvelopeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
