// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"tmail/ent/envelope"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Envelope is the model entity for the Envelope schema.
type Envelope struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// To holds the value of the "to" field.
	To string `json:"to,omitempty"`
	// From holds the value of the "from" field.
	From string `json:"from,omitempty"`
	// Subject holds the value of the "subject" field.
	Subject string `json:"subject,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EnvelopeQuery when eager-loading is set.
	Edges        EnvelopeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EnvelopeEdges holds the relations/edges for other nodes in the graph.
type EnvelopeEdges struct {
	// Attachments holds the value of the attachments edge.
	Attachments []*Attachment `json:"attachments,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AttachmentsOrErr returns the Attachments value or an error if the edge
// was not loaded in eager-loading.
func (e EnvelopeEdges) AttachmentsOrErr() ([]*Attachment, error) {
	if e.loadedTypes[0] {
		return e.Attachments, nil
	}
	return nil, &NotLoadedError{edge: "attachments"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Envelope) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case envelope.FieldID:
			values[i] = new(sql.NullInt64)
		case envelope.FieldTo, envelope.FieldFrom, envelope.FieldSubject, envelope.FieldContent:
			values[i] = new(sql.NullString)
		case envelope.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Envelope fields.
func (_m *Envelope) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case envelope.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case envelope.FieldTo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field to", values[i])
			} else if value.Valid {
				_m.To = value.String
			}
		case envelope.FieldFrom:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from", values[i])
			} else if value.Valid {
				_m.From = value.String
			}
		case envelope.FieldSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject", values[i])
			} else if value.Valid {
				_m.Subject = value.String
			}
		case envelope.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case envelope.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Envelope.
// This includes values selected through modifiers, order, etc.
func (_m *Envelope) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAttachments queries the "attachments" edge of the Envelope entity.
func (_m *Envelope) QueryAttachments() *AttachmentQuery {
	return NewEnvelopeClient(_m.config).QueryAttachments(_m)
}

// Update returns a builder for updating this Envelope.
// Note that you need to call Envelope.Unwrap() before calling this method if this Envelope
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Envelope) Update() *EnvelopeUpdateOne {
	return NewEnvelopeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Envelope entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Envelope) Unwrap() *Envelope {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Envelope is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Envelope) String() string {
	var builder strings.Builder
	builder.WriteString("Envelope(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("to=")
	builder.WriteString(_m.To)
	builder.WriteString(", ")
	builder.WriteString("from=")
	builder.WriteString(_m.From)
	builder.WriteString(", ")
	builder.WriteString("subject=")
	builder.WriteString(_m.Subject)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Envelopes is a parsable slice of Envelope.
type Envelopes []*Envelope
