// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"tmail/ent/attachment"
	"tmail/ent/envelope"
	"tmail/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EnvelopeUpdate is the builder for updating Envelope entities.
type EnvelopeUpdate struct {
	config
	hooks    []Hook
	mutation *EnvelopeMutation
}

// Where appends a list predicates to the EnvelopeUpdate builder.
func (_u *EnvelopeUpdate) Where(ps ...predicate.Envelope) *EnvelopeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTo sets the "to" field.
func (_u *EnvelopeUpdate) SetTo(v string) *EnvelopeUpdate {
	_u.mutation.SetTo(v)
	return _u
}

// SetNillableTo sets the "to" field if the given value is not nil.
func (_u *EnvelopeUpdate) SetNillableTo(v *string) *EnvelopeUpdate {
	if v != nil {
		_u.SetTo(*v)
	}
	return _u
}

// SetFrom sets the "from" field.
func (_u *EnvelopeUpdate) SetFrom(v string) *EnvelopeUpdate {
	_u.mutation.SetFrom(v)
	return _u
}

// SetNillableFrom sets the "from" field if the given value is not nil.
func (_u *EnvelopeUpdate) SetNillableFrom(v *string) *EnvelopeUpdate {
	if v != nil {
		_u.SetFrom(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *EnvelopeUpdate) SetSubject(v string) *EnvelopeUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *EnvelopeUpdate) SetNillableSubject(v *string) *EnvelopeUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *EnvelopeUpdate) SetContent(v string) *EnvelopeUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *EnvelopeUpdate) SetNillableContent(v *string) *EnvelopeUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *EnvelopeUpdate) SetCreatedAt(v time.Time) *EnvelopeUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *EnvelopeUpdate) SetNillableCreatedAt(v *time.Time) *EnvelopeUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (_u *EnvelopeUpdate) AddAttachmentIDs(ids ...string) *EnvelopeUpdate {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (_u *EnvelopeUpdate) AddAttachments(v ...*Attachment) *EnvelopeUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// Mutation returns the EnvelopeMutation object of the builder.
func (_u *EnvelopeUpdate) Mutation() *EnvelopeMutation {
	return _u.mutation
}

// ClearAttachments clears all "attachments" edges to the Attachment entity.
func (_u *EnvelopeUpdate) ClearAttachments() *EnvelopeUpdate {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to Attachment entities by IDs.
func (_u *EnvelopeUpdate) RemoveAttachmentIDs(ids ...string) *EnvelopeUpdate {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to Attachment entities.
func (_u *EnvelopeUpdate) RemoveAttachments(v ...*Attachment) *EnvelopeUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EnvelopeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnvelopeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EnvelopeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnvelopeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnvelopeUpdate) check() error {
	if v, ok := _u.mutation.To(); ok {
		if err := envelope.ToValidator(v); err != nil {
			return &ValidationError{Name: "to", err: fmt.Errorf(`ent: validator failed for field "Envelope.to": %w`, err)}
		}
	}
	if v, ok := _u.mutation.From(); ok {
		if err := envelope.FromValidator(v); err != nil {
			return &ValidationError{Name: "from", err: fmt.Errorf(`ent: validator failed for field "Envelope.from": %w`, err)}
		}
	}
	return nil
}

func (_u *EnvelopeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(envelope.Table, envelope.Columns, sqlgraph.NewFieldSpec(envelope.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.To(); ok {
		_spec.SetField(envelope.FieldTo, field.TypeString, value)
	}
	if value, ok := _u.mutation.From(); ok {
		_spec.SetField(envelope.FieldFrom, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(envelope.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(envelope.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(envelope.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   envelope.AttachmentsTable,
			Columns: []string{envelope.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   envelope.AttachmentsTable,
			Columns: []string{envelope.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   envelope.AttachmentsTable,
			Columns: []string{envelope.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{envelope.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EnvelopeUpdateOne is the builder for updating a single Envelope entity.
type EnvelopeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EnvelopeMutation
}

// SetTo sets the "to" field.
func (_u *EnvelopeUpdateOne) SetTo(v string) *EnvelopeUpdateOne {
	_u.mutation.SetTo(v)
	return _u
}

// SetNillableTo sets the "to" field if the given value is not nil.
func (_u *EnvelopeUpdateOne) SetNillableTo(v *string) *EnvelopeUpdateOne {
	if v != nil {
		_u.SetTo(*v)
	}
	return _u
}

// SetFrom sets the "from" field.
func (_u *EnvelopeUpdateOne) SetFrom(v string) *EnvelopeUpdateOne {
	_u.mutation.SetFrom(v)
	return _u
}

// SetNillableFrom sets the "from" field if the given value is not nil.
func (_u *EnvelopeUpdateOne) SetNillableFrom(v *string) *EnvelopeUpdateOne {
	if v != nil {
		_u.SetFrom(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *EnvelopeUpdateOne) SetSubject(v string) *EnvelopeUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *EnvelopeUpdateOne) SetNillableSubject(v *string) *EnvelopeUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *EnvelopeUpdateOne) SetContent(v string) *EnvelopeUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *EnvelopeUpdateOne) SetNillableContent(v *string) *EnvelopeUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *EnvelopeUpdateOne) SetCreatedAt(v time.Time) *EnvelopeUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *EnvelopeUpdateOne) SetNillableCreatedAt(v *time.Time) *EnvelopeUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (_u *EnvelopeUpdateOne) AddAttachmentIDs(ids ...string) *EnvelopeUpdateOne {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (_u *EnvelopeUpdateOne) AddAttachments(v ...*Attachment) *EnvelopeUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// Mutation returns the EnvelopeMutation object of the builder.
func (_u *EnvelopeUpdateOne) Mutation() *EnvelopeMutation {
	return _u.mutation
}

// ClearAttachments clears all "attachments" edges to the Attachment entity.
func (_u *EnvelopeUpdateOne) ClearAttachments() *EnvelopeUpdateOne {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to Attachment entities by IDs.
func (_u *EnvelopeUpdateOne) RemoveAttachmentIDs(ids ...string) *EnvelopeUpdateOne {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to Attachment entities.
func (_u *EnvelopeUpdateOne) RemoveAttachments(v ...*Attachment) *EnvelopeUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// Where appends a list predicates to the EnvelopeUpdate builder.
func (_u *EnvelopeUpdateOne) Where(ps ...predicate.Envelope) *EnvelopeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EnvelopeUpdateOne) Select(field string, fields ...string) *EnvelopeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Envelope entity.
func (_u *EnvelopeUpdateOne) Save(ctx context.Context) (*Envelope, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnvelopeUpdateOne) SaveX(ctx context.Context) *Envelope {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EnvelopeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnvelopeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnvelopeUpdateOne) check() error {
	if v, ok := _u.mutation.To(); ok {
		if err := envelope.ToValidator(v); err != nil {
			return &ValidationError{Name: "to", err: fmt.Errorf(`ent: validator failed for field "Envelope.to": %w`, err)}
		}
	}
	if v, ok := _u.mutation.From(); ok {
		if err := envelope.FromValidator(v); err != nil {
			return &ValidationError{Name: "from", err: fmt.Errorf(`ent: validator failed for field "Envelope.from": %w`, err)}
		}
	}
	return nil
}

func (_u *EnvelopeUpdateOne) sqlSave(ctx context.Context) (_node *Envelope, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(envelope.Table, envelope.Columns, sqlgraph.NewFieldSpec(envelope.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Envelope.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, envelope.FieldID)
		for _, f := range fields {
			if !envelope.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != envelope.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.To(); ok {
		_spec.SetField(envelope.FieldTo, field.TypeString, value)
	}
	if value, ok := _u.mutation.From(); ok {
		_spec.SetField(envelope.FieldFrom, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(envelope.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(envelope.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(envelope.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   envelope.AttachmentsTable,
			Columns: []string{envelope.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   envelope.AttachmentsTable,
			Columns: []string{envelope.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   envelope.AttachmentsTable,
			Columns: []string{envelope.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Envelope{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{envelope.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
